name: main

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: CI Build
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-overwrite-existing: true

      - name: Create Sign File
        run: |
          touch signing.properties
          echo storePassword=${{ secrets.KEY_STORE_PASSWORD }} >> signing.properties
          echo keyAlias=${{ secrets.KEY_ALIAS }} >> signing.properties
          echo keyPassword='${{ secrets.KEY_STORE_PASSWORD }}' >> signing.properties
          echo storeFile=../keystore.jks >> signing.properties
          echo ${{ secrets.KEY_DATA }} | base64 --decode > keystore.jks

      - name: Build Release
        run: |
          bash gradlew assembleRelease

      - name: Build Debug
        run: |
          bash gradlew assembleDebug

      - name: Find APKs
        run: |
          echo "APK_FILE_RELEASE=$(find app/build/outputs/apk/release -name '*.apk')" >> $GITHUB_ENV
          echo "APK_FILE_DEBUG=$(find app/build/outputs/apk/debug -name '*.apk')" >> $GITHUB_ENV
          
      - name: Show Artifacts SHA256
        run: |
          echo "### Build Success :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "|ABI|SHA256|" >> $GITHUB_STEP_SUMMARY
          echo "|:--------:|:----------|" >> $GITHUB_STEP_SUMMARY
          release=($(sha256sum ${{ env.APK_FILE_RELEASE }}))
          echo "|Release|$release" >> $GITHUB_STEP_SUMMARY
          debug=($(sha256sum ${{ env.APK_FILE_DEBUG }}))
          echo "|Debug|$debug" >> $GITHUB_STEP_SUMMARY

      - name: Upload Artifacts Release
        uses: actions/upload-artifact@v4
        with:
          name: FoldDevtools-release-${{ github.event.head_commit.id }}
          path: ${{ env.APK_FILE_RELEASE }}
      - name: Upload Artifacts Debug
        uses: actions/upload-artifact@v4
        with:
          name: FoldDevtools-debug-${{ github.event.head_commit.id }}
          path: ${{ env.APK_FILE_DEBUG }}
